services:
  postgres:
    image: postgres
    container_name: grpc-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - grpc_user_network
    volumes:
      - userpostgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-api-gateway:
    image: grpc-user-api-gateway
    restart: always
    depends_on:
      - postgres
    container_name: grpc-user-api-gateway
    networks:
      - grpc_user_network
    ports:
      - "3000:3000"

  user-services:
    image: grpc-user-service
    restart: always
    depends_on:
      - postgres
    container_name: grpc-user-service
    networks:
      - grpc_user_network
    hostname: grpc-user-service

networks:
  grpc_user_network:
    driver: bridge

volumes:
  userpostgres-volume:
